// AUTO-GENERATED by scripts/generate-skills-atlas.mjs — do not edit by hand.
// Maps each icon path to its UV offset/repeat within /skills-atlas.webp.
export const ATLAS_TEXTURE = '/skills-atlas.webp';
export const ATLAS_MAP = {
  "/reactsjs.png": {
    "offset": [
      0,
      0.75
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/nextjs.png": {
    "offset": [
      0.25,
      0.75
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/typescript.png": {
    "offset": [
      0.5,
      0.75
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/js.png": {
    "offset": [
      0.75,
      0.75
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/nodejs.png": {
    "offset": [
      0,
      0.5
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/java.png": {
    "offset": [
      0.25,
      0.5
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/springboot.png": {
    "offset": [
      0.5,
      0.5
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/firebase.png": {
    "offset": [
      0.75,
      0.5
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/mongodb.png": {
    "offset": [
      0,
      0.25
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/sql.png": {
    "offset": [
      0.25,
      0.25
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/git.png": {
    "offset": [
      0.5,
      0.25
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/unity.png": {
    "offset": [
      0.75,
      0.25
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/c.png": {
    "offset": [
      0,
      0
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/c-sharp.png": {
    "offset": [
      0.25,
      0
    ],
    "repeat": [
      0.25,
      0.25
    ]
  },
  "/c++.png": {
    "offset": [
      0.5,
      0
    ],
    "repeat": [
      0.25,
      0.25
    ]
  }
};
